name: Tim MacDonald
favicon: null
layout_spectrum: 0.9260547545272857
typography_spectrum: 0.058196717873215675
title: Tim MacDonald Music
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#98b9d1'
    - '#5e4646'
    - '#0b5c78'
    - '#8e6755'
    - '#1c2d2d'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.9935948655474931
  rhythmicContrast: 1
purpose: []
