name: Tim MacDonald
favicon: null
layout_spectrum: 0.9260547545272857
typography_spectrum: 0.058196717873215675
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.3679777707438916
  lightness: 0.3246164647862315
  saturation: 0.9935948655474931
  rhythmicContrast: 0.025405859807506204
purpose: []
